sudo: false

language:
  - python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "nightly"

install:
  - "pip install -r requirements.txt"
  - pip install pytest-cov python-coveralls
#  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
#    then pip install pytest-cov python-coveralls;
#    else pip install pytest;
#    fi
#  - pip install pep8

script:
  - py.test -vv example.py
  - python -m coverage run example.py
#  - pep8 example.py
#  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
#    then py.test -vv example.py --cov example.py;
#    else py.test -vv example.py;
#    fi

#after_success:
#  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
#    then coveralls;
#    fi

notifications:
email: false
